name: master

on:
  push:
    branches: [ master ]

env:
  APP_SIGN_KEYSTORE_PATH: /tmp/keystore
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Write key file
        env:
          AUTH: ${{ secrets.QA_KEYSTORE }}
        run: echo $AUTH | base64 --decode > /tmp/keystore

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bundler cache
        uses: actions/cache@v1
        with:
          path: $CACHE_BUNDLER
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: install dependencies
        run: gem install bundler && bundle install

      - name: fastlane develop
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: develop
          options: '{ "conf": "release" }'
          skip-tracking: false
          subdirectory: fastlane
          bundle-install-path: CACHE_BUNDLER